version: '3.1'
services:
  app:
    build:
      context: ../app
      dockerfile: Dockerfile
      args:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USER=user1
        - DB_PASSWORD=password
        - DB_NAME=app
        - INPUT_FILE=files/input.txt
    container_name: app
    networks:
      - app-network
    depends_on:
      - db  
  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    container_name: db
    networks:
      - app-network
  testdb:
    build:
      context: ../db
      dockerfile: Dockerfile
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    container_name: testdb
    networks:
      - app-network
networks:
  app-network:
   name: app-network
